# Importing Libraries

In [2]:
import numpy as np
import pandas as pd

# Importing Dataset of Movies Between 2010-2019

In [3]:
movie_b = pd.read_csv('hindi/bollywood_2010-2019.csv')
movie_a = pd.read_csv('hindi/bollywood_1990-2009.csv')

In [67]:
movies = pd.concat([movie_a, movie_b])
movies

,title,imdb_id,poster_path,wiki_link
0,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots
1,Luck by Chance,tt0886539,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Luck_by_Chance
2,Love Aaj Kal,tt1275863,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Love_Aaj_Kal
3,Wanted (2009 film),tt1084972,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Wanted_(2009_film)
4,Delhi-6,tt1043451,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Delhi-6
...,...,...,...,...
975,Dulha Mil Gaya,tt1182884,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dulha_Mil_Gaya
976,Anjaana Anjaani,tt1499201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Anjaana_Anjaani
977,Dunno Y... Na Jaane Kyon,tt1742307,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dunno_Y..._Na_Ja...
978,Pankh,tt1124386,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pankh_(film)
979,Action Replayy,tt1396208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Action_Replayy

In [76]:
meta_a = pd.read_csv('bollywood_meta_1990-2009.csv')
meta_b = pd.read_csv('bollywood_meta_2010-2019.csv')
meta = pd.concat([meta_a, meta_b])

In [77]:
movies = pd.concat([movies, meta])

In [78]:
movies

,imdb_id,story,summary,tagline,actors,wins_nominations,release_date,title,original_title,is_adult,year_of_release,runtime,genres
0,tt1187043,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India),NaN,NaN,NaN,NaN,NaN,NaN
1,tt1275863,London-based Jai Vardhan Singh and Meera Pandi...,An old-fashioned romantic tells his personal l...,NaN,Saif Ali Khan|Deepika Padukone|Rishi Kapoor|Ra...,12 wins & 33 nominations,31 July 2009 (India),NaN,NaN,NaN,NaN,NaN,NaN
2,tt1340838,Attractive ramp model Nandita Chopra has a b...,An artist comes to realize that the woman he h...,NaN,Kangana Ranaut|Adhyayan Suman|Emraan Hashmi|,NaN,23 January 2009 (India),NaN,NaN,NaN,NaN,NaN,NaN
3,tt1252596,A statue in a town's square narrates to a jour...,The wacky adventures of a young man who is wil...,NaN,Ranbir Kapoor|Katrina Kaif|Darshan Jariwala|Sm...,6 wins & 6 nominations,6 November 2009 (India),NaN,NaN,NaN,NaN,NaN,NaN
4,tt1084972,Mumbai-based middle-classed Jhanvi who lives ...,Radhe is a ruthless gangster who will kill any...,MAFIA WANTS HIM DEAD| POLICE WANTS HIM ALIVE,Salman Khan|Ayesha Takia|Vinod Khanna|Govind N...,1 win & 4 nominations,25 September 2009 (USA),NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,tt9496212,NaN,NaN,NaN,NaN,NaN,NaN,22 Yards,22 Yards,0.0,2019,126,Sport
925,tt9558612,NaN,NaN,NaN,NaN,NaN,NaN,PM Narendra Modi,PM Narendra Modi,0.0,2019,136,Biography|Drama
926,tt9574388,NaN,NaN,NaN,NaN,NaN,NaN,Bachche Kachche Sachche,Bachche Kachche Sachche,0.0,2017,\N,Drama|Short
927,tt9680136,NaN,NaN,NaN,NaN,NaN,NaN,Pati Patni Aur Woh,Pati Patni Aur Woh,0.0,2019,\N,Comedy|Romance
928,tt9795264,NaN,NaN,NaN,NaN,NaN,NaN,Risknamaa,Risknamaa,0.0,2019,123,Thriller

In [72]:
text_a = pd.read_csv('bollywood_text_1990-2009.csv')
text_b = pd.read_csv('bollywood_text_1990-2009.csv')

In [73]:
movies = pd.concat([text_a, text_b])

In [74]:
movies

,imdb_id,story,summary,tagline,actors,wins_nominations,release_date
0,tt1187043,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
1,tt1275863,London-based Jai Vardhan Singh and Meera Pandi...,An old-fashioned romantic tells his personal l...,NaN,Saif Ali Khan|Deepika Padukone|Rishi Kapoor|Ra...,12 wins & 33 nominations,31 July 2009 (India)
2,tt1340838,Attractive ramp model Nandita Chopra has a b...,An artist comes to realize that the woman he h...,NaN,Kangana Ranaut|Adhyayan Suman|Emraan Hashmi|,NaN,23 January 2009 (India)
3,tt1252596,A statue in a town's square narrates to a jour...,The wacky adventures of a young man who is wil...,NaN,Ranbir Kapoor|Katrina Kaif|Darshan Jariwala|Sm...,6 wins & 6 nominations,6 November 2009 (India)
4,tt1084972,Mumbai-based middle-classed Jhanvi who lives ...,Radhe is a ruthless gangster who will kill any...,MAFIA WANTS HIM DEAD| POLICE WANTS HIM ALIVE,Salman Khan|Ayesha Takia|Vinod Khanna|Govind N...,1 win & 4 nominations,25 September 2009 (USA)
...,...,...,...,...,...,...,...
1526,tt0360145,Widower Chandrakant lives poor lifestyle in In...,Veeru takes lonely Rekha as his sister. Rekha ...,NaN,Dharmendra|Amrita Singh|Aditya Pancholi|Farha ...,NaN,NaN
1527,tt0098461,Thakur Azghar Singh lord over a small Indian v...,A policeman is killed in a brawl - one of his ...,NaN,Jeetendra|Sanjay Dutt|Jaya Prada|Madhuri Dixit...,NaN,10 December 1990 (India)
1528,tt0370090,NaN,Add a Plot »,NaN,Rajiv Kapoor|Anita Raj|Kimi Katkar|Ranjeet|Vin...,NaN,6 September 1990 (India)
1529,tt0173283,Living in a posh mansion named Swarg this is ...,Living in a posh mansion named Swarg this is ...,NaN,Rajesh Khanna|Govinda|Madhavi|Juhi Chawla|Dili...,NaN,2 May 1990 (India)
1530,tt0155147,CBI Inspector Kumar is assigned to investigate...,CBI Inspector Kumar is assigned to investigate...,NaN,Dev Anand|Sonika Gill|Vikram Gokhale|Bharat Ka...,NaN,20 December 1991 (India)